# Change these first
owner: fuhji # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: BGS
    url: https://www.bgs.ac.uk/
  - name: INHFL GraphQL UAT
    url: https://inhfl-api-uat.bgs.ac.uk/browser/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: |
      { "query": "{ __typename }" }
    expectedStatusCodes:
      - 401





status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "INHFL Monitoring"
  introMessage: Intro
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
