# Change these first
owner: fuhji # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: INHFL GUI UAT
    url: https://inhfl-uat.bgs.ac.uk/
  - name: INHFL GraphQL UAT
    url: https://inhfl-api-uat.bgs.ac.uk/browser/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: |
      { "query": "{ __typename }" }
    expectedStatusCodes:
      - 401





status-website:
  themeUrl: https://github.com/Fuhji/upptime/blob/master/assets/theme.css
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: INHFL Monitoring
  introTitle: "INHFL Monitoring"
  introMessage: Automated monitoring of INHFL services.
  navbar:


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
